### ISSUE TITLE
Question about visualizing dislocation structures using Ovito

### ISSUE THREAD

**Issue by Colin-Williams94843** [OpenDiS/OpenDiS#3]
Hello OpenDiS team,

I apologize if this is the wrong forum to ask a question about using OpenDiS, but I did not see a contact on the documentation yet. 

I have successfully installed/compiled OpenDiS on Mac and have been experimenting with the available example scripts. I am successfully running Example 10 - "Strain Hardening" and would like to visualize the dislocation arrangements using Ovito as instructed. 

When I attempt to open the file showing the initial configuration ("180chains_16.10e.data") in Ovito (basic version), I get an error message stating, "Could not auto-detect the format of the file 180chains_16.10e.data. The file format might not be supported." 

I have tried to open the file with as all of the supported file types within Ovito, but was not successful in visualizing the dislocations. The file will open as a LAMMPS data file, but based on the appearance of the Ovito GUI (compared to the Ovito screenshot in the documentation), this is not correct. 

Is there something that must be done to the file in order to properly open it in Ovito that is not stated in the documentation? 

Thank you for your reply.

**Comment by nnn911** [comment]
Hi,

I'm not a member of the OpenDis team; I'm with the OVITO team. You are correct that the file you provided cannot be opened by OVITO as it stands. To address this, I built a [custom file reader](https://www.ovito.org/manual/python/introduction/custom_file_readers.html) specifically for this format.

Currently, the file reader is somewhat limited—it works for this file and others that follow the same schema, but it might not work for all files generated by OpenDis. This is mostly because I haven't had the opportunity to work with OpenDis myself; I've only looked at this specific file to understand the meaning of each row or value.

There is one significant limitation to note: the OVITO Python interface currently does not support the creation of [dislocation networks](https://www.ovito.org/manual/python/modules/ovito_data.html#ovito.data.DislocationNetwork) in the same way the DXA modifier does. Therefore, this file reader interprets the "nodes" as [particles](https://www.ovito.org/manual/python/modules/ovito_data.html#ovito.data.Lines) and the "dislocation lines" or "arms" as [lines](https://www.ovito.org/manual/python/modules/ovito_data.html#ovito.data.Lines). We are working to overcome this limitation.

Please let me know if you encounter any issues or have any feedback.

Here is the file loaded into OVITO:
![image](https://github.com/user-attachments/assets/02a615d7-5c14-45b6-9d3d-dd6c62635a3a)

The repository for this file reader is available [here](https://github.com/ovito-org/OpenDiSFileReader). You can install it into OVITO using the following methods:

For OVITO Pro with the [integrated Python interpreter](https://docs.ovito.org/python/introduction/installation.html#ovito-pro-integrated-interpreter):
```
ovitos -m pip install --user git+https://github.com/ovito-org/OpenDiSFileReader.git
```
The `--user` option is recommended as it [installs the package in the user's site directory](https://pip.pypa.io/en/stable/user_guide/#user-installs).

For other Python interpreters or Conda environments:
```
pip install git+https://github.com/ovito-org/OpenDiSFileReader.git
```

**Comment by Colin-Williams94843** [comment]
Daniel, 

Thank you for your reply. I have attempted to install Ovito using the command line tools within Anaconda (on Mac), as well as the custom file reader you created. Despite

**Comment by Colin-Williams94843** [comment]
Thank you for your reply! I will follow these instructions and follow-up if I encounter any future issues.

**Comment by lbborkowski** [comment]
@Colin-Williams94843 - Were you able to install the custom file reader and open the OpenDiS file with Ovito Basic? I can install using the instructions provided by @nnn911 for "other Python interpreters or Conda environments" but it's not clear how to integrate with the basic version of Ovito.

**Comment by Colin-Williams94843** [comment]
@lbborkowski @nnn911 - I have been traveling the past week and was not yet able to succeed in visualizing these dislocation structures yet using Ovito on my Mac (in a conda environment). I just tried it out tonight.

Maybe you can catch my mistake. 

In the terminal, I used the given command: 

pip install git+https://github.com/ovito-org/OpenDiSFileReader.git

and Ovito seems to install successfully. However, when trying to run Ovito after this from the command line, or even trying to find its location using "which" I am not able to see Ovito from the command line.

I am also using Ovito basic - is this a problem?

Thank you both for your help.

**Comment by nnn911** [comment]
OVITO Basic does not include an embedded Python interpreter and cannot execute Python-based extensions like this custom file format reader. The only way to use this extension is either via OVITO Pro (license required) or the OVITO Python Module (free of charge). The latter lets you develop standalone Python scripts (without an interactive GUI) that load, process, and render images/animations of the simulation programatically. Both OVITO Pro and the OVITO Python Module for Conda can be obtained by installing the OVITO package from our channel (not conda-forge), reference[Get OVITO](https://www.ovito.org/#download) or the [user manual](https://docs.ovito.org/python/introduction/installation.html) for more information.

**Comment by lbborkowski** [comment]
@Colin-Williams94843 - I was able to plot the dislocation network using the Python API with Ovito Basic. I installed Ovito and the Custom File Reader in a conda environment using the conda and pip install commands below.

`conda install --strict-channel-priority -c https://conda.ovito.org -c conda-forge ovito=3.11.0`

`pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org git+https://github.com/ovito-org/OpenDiSFileReader.git`

I added the lines below to the \_\_init\_\_.py code provided in the file reader then renamed and executed it.

```
import math
from ovito.vis import Viewport
from ovito.vis import ColorLegendOverlay, Viewport
from ovito.qt_compat import QtCore
from ovito.modifiers import *

pipeline = import_file("180chains_16.10e.data", input_format=OpenDiSFileReader)
modifier = ColorCodingModifier(property='Position.Y', operate_on='lines')
pipeline.modifiers.append(modifier)
pipeline.add_to_scene()

vp = Viewport()
vp.camera_dir = (2, 3, -3)
vp.zoom_all()
vp.render_image(filename="myimage12.png", size=(800,600))
```

@nnn911 - Could you please provide guidance on how to reproduce the image in your post using the Python API. I'm able to generate something similar using the code above but the coloring, angle, etc. are different.

**Comment by nnn911** [comment]
I have added the full Python code (automatically generated [here](https://www.ovito.org/docs/current/advanced_topics/code_generation.html)) for the example to the [repository](https://github.com/ovito-org/OpenDiSFileReader/blob/main/examples/ReaderExample_02.py).

In the original image, the colors were based on the local line orientation. I modified this to use the plane normal component from the original file instead. While this results in slightly different coloring, it makes more sense for this example.
